baseURL = "https://example.com/"
languageCode = "en-us"
title = "Introduction to Neural Networks"
disableKinds = ["sitemap", "RSS"]
theme = "."
themesDir = "../"

# uncomment for browsing at file:///
relativeURLs = true
uglyURLs = true

[author]
name = "Raphael Cobe"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"
